### ISSUE TITLE
Media could not be loaded

### ISSUE THREAD

**Issue by VaibhavArora19** [livepeer/webrtmp-sdk#5]
While using webrmtp-sdk the live streaming does start, but in the livepeer dashboard it is showing that media could not be loaded, either because the server or network failed or because the format is not supported. Is there any way to fix that?

**Comment by Disha1998** [comment]
Same issue I'm getting while using --- npm i @livepeer/webrtmp-sdk --- please fix this out! #livepeer

> While using webrmtp-sdk the live streaming does start, but in the livepeer dashboard it is showing that media could not be loaded, either because the server or network failed or because the format is not supported. Is there any way to fix that?

**Comment by VaibhavArora19** [comment]
Hey @Disha1998, if you reside in India then livepeer nodes doesn't work here, this has been confirmed by one of the members of livepeer. Connect to a vpn and switch to either france or usa to make it work.

**Comment by Disha1998** [comment]
> Hey @Disha1998, if you reside in India then livepeer nodes doesn't work here, this has been confirmed by one of the members of livepeer. Connect to a vpn and switch to either france or usa to make it work.

Hiii, @VaibhavArora19  Thanks for leting me know this :)
